### ISSUE TITLE
Temp Mail

### ISSUE THREAD

**Issue by YatharthaRana** [Novus-Neurons/Online-tools#2]
I would like to add the website that provides with the temporary mail address

**Comment by gamedevCloudy** [comment]
Feel free to fork and add it.

**Comment by YatharthaRana** [comment]
Will it help me in hacktober fest ??

**Comment by gamedevCloudy** [comment]
> 

Yes, we are trying to make this for beginners, primarily our fellow classmates.

**Comment by Hrushi11** [comment]
Resolved.
